doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        types:
            foo.foo_id: App\Context\Foo\Infrastructure\Persistence\Doctrine\CustomType\FooIdType
            foo.bar_id: App\Context\Foo\Infrastructure\Persistence\Doctrine\CustomType\BarIdType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            AppFoo:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Context/Foo/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Context\Foo\Domain\Write'
                alias: AppFoo
