framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            ampqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: App\Shared\Infrastructure\Bus\Serializer\MessengerDomainEventJsonSerializer

        default_bus: command.bus
        buses:
            command.bus:
            query.bus:
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Shared\Infrastructure\Bus\Middleware\MessengerDomainEventLogMiddleware
        routing:
            'App\Shared\Domain\Bus\Event\DomainEvent': ampqp
