framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            ampqp:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            kafka:
                dsn: '%env(MESSENGER_KAFKA_TRANSPORT_DSN)%'

        default_bus: sync.command.bus
        buses:
            sync.command.bus:
                middleware:
                    - App\Shared\Infrastructure\Bus\Middleware\MessengerIdStampMiddleware
                    - App\Shared\Infrastructure\Bus\Middleware\MessengerLoggerMiddleware
                    - doctrine_transaction
            sync.query.bus:
                middleware:
                    - App\Shared\Infrastructure\Bus\Middleware\MessengerIdStampMiddleware
                    - App\Shared\Infrastructure\Bus\Middleware\MessengerLoggerMiddleware
            async.event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Shared\Infrastructure\Bus\Middleware\MessengerIdStampMiddleware
                    - App\Shared\Infrastructure\Bus\Middleware\MessengerEventLogMiddleware
        routing:
            #'App\Shared\Domain\Write\Event\DomainEvent': ampqp
            'App\Shared\Domain\Write\Event\DomainEvent': kafka
        serializer:
            default_serializer: App\Shared\Infrastructure\Bus\Serializer\MessengerMessageSerializer
