App\Context\Foo\Domain\Write\Foo:
  type: entity
  repositoryClass: App\Context\Foo\Infrastructure\Persistence\Repository\DoctrineFooRepository
  table: foo
  id:
    id:
      type: foo.foo_id
      generator:
        strategy: NONE
  fields:
    name:
      type: string
    createdAt:
      type: datetime_immutable

  oneToMany:
    bars:
      targetEntity: App\Context\Foo\Domain\Write\Bar\Bar
      cascade: ['all']
      mappedBy: foo
