get_foo:
  path: /foo/{fooId}
  methods: GET
  controller: App\UI\Controller\GetFooController

get_all_foo:
  path: /foo
  methods: GET
  controller: App\UI\Controller\GetAllFooController

put_foo:
  path: /foo/{fooId}
  methods: PUT
  controller: App\UI\Controller\PutFooController

delete_foo:
  path: /foo/{fooId}
  methods: DELETE
  controller: App\UI\Controller\DeleteFooController

post_foo:
  path: /foo
  methods: POST
  controller: App\UI\Controller\PostFooController
