get_v1_foo:
  path: /v1/foo/{fooId}
  methods: GET
  controller: App\UI\Controller\GetFooController

get_v1_all_foo:
  path: /v1/foo
  methods: GET
  controller: App\UI\Controller\GetAllFooController

put_v1_foo:
  path: /v1/foo/{fooId}
  methods: PUT
  controller: App\UI\Controller\PutFooController

delete_v1_foo:
  path: /v1/foo/{fooId}
  methods: DELETE
  controller: App\UI\Controller\DeleteFooController

post_v1_foo:
  path: /v1/foo
  methods: POST
  controller: App\UI\Controller\PostFooController
